module.exports = {
  chainID: "phoenix-1",
  name: "Terra (LUNA)",
  networkType: "mainnet",
  lcd: "https://terra-lcd.publicnode.com",
  api: "https://terra-lcd.publicnode.com",
  rpc: "https://terra-rpc.publicnode.com:443",
  prefix: "terra",
  coinType: 330,
  baseAsset: "uluna",
  gasAdjustment: 1.75,
  gasPrices: {
    uluna: 28.325,
  },
  icon: "/img/chains/Terra.svg",
  alliance: false,
  explorer: {
    address: "https://finder.terra.money/mainnet/address/{}",
    tx: "https://finder.terra.money/mainnet/tx/{}",
    validator: "https://finder.terra.money/mainnet/validator/{}",
    block: "https://finder.terra.money/mainnet/block/{}",
  },
  channels: {
    "akashnet-2": "channel-56",
    "axelar-dojo-1": "channel-11",
    "carbon-1": "channel-12",
    "cheqd-mainnet-1": "channel-9",
    "chihuahua-1": "channel-34",
    "comdex-1": "channel-51",
    "cosmoshub-4": "channel-339",
    "crescent-1": "channel-27",
    "mainnet-3": "channel-99",
    "juno-1": "channel-86",
    "kaiyo-1": "channel-5",
    "mars-1": "channel-2",
    "migaloo-1": "channel-0",
    "osmosis-1": "channel-251",
    "pacific-1": "channel-3",
    "stafihub-1": "channel-9",
    "stride-1": "channel-52",
  },
};
