import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const sourceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = path.resolve(sourceRoot, "..", "..");
const srcRoot = path.join(sourceRoot, "src");
const distRoot = path.resolve(process.env.DO_WALLET_FRONTEND_OUT || path.join(workspaceRoot, "current", "frontend"));
const config = JSON.parse(await readFile(path.join(srcRoot, "build-config.json"), "utf8"));

function assertInside(parent, child) {
  const relative = path.relative(parent, child);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Refusing to write outside ${parent}: ${child}`);
  }
}

async function copyIfExists(from, to) {
  if (!existsSync(from)) return;
  await mkdir(path.dirname(to), { recursive: true });
  await cp(from, to, { recursive: true });
}

async function bundleCss() {
  const chunks = [];
  for (const file of config.styles) {
    const css = await readFile(path.join(srcRoot, "styles", file), "utf8");
    chunks.push(`/*! ${file} */\n${css.trim()}\n`);
  }
  await mkdir(path.join(distRoot, "static", "css"), { recursive: true });
  await writeFile(path.join(distRoot, "static", "css", "do-wallet-v2-styles.css"), chunks.join("\n"), "utf8");
}

async function bundleRuntime(files, folder, outputFile) {
  const chunks = [
    `/*! Generated by source/frontend/scripts/build.mjs. Do not edit generated output directly. */`,
    `(function(){`,
    `"use strict";`,
    `function runModule(name, moduleFactory) {`,
    `  try { moduleFactory(); }`,
    `  catch (error) {`,
    `    try {`,
    `      console.error("[Do-Wallet runtime]", name, error);`,
    `      document.documentElement.setAttribute("data-do-wallet-runtime-error", name);`,
    `    } catch (innerError) {}`,
    `  }`,
    `}`,
  ];
  for (const file of files) {
    const code = await readFile(path.join(srcRoot, "runtime", folder, file), "utf8");
    chunks.push(`runModule(${JSON.stringify(file)}, function(){\n${code.trim()}\n});`);
  }
  chunks.push(`})();`);
  await mkdir(path.join(distRoot, "static", "js"), { recursive: true });
  await writeFile(path.join(distRoot, "static", "js", outputFile), chunks.join("\n\n"), "utf8");
}

async function writeIndex() {
  const template = await readFile(path.join(srcRoot, "index.template.html"), "utf8");
  const standaloneAfterMain = (config.standaloneAfterMain || [])
    .map((file) => `    <script defer src="/static/js/${file}?v=${config.build}"></script>`)
    .join("\n");
  await writeFile(
    path.join(distRoot, "index.html"),
    template
      .replaceAll("__BUILD__", config.build)
      .replace("__STANDALONE_AFTER_MAIN_SCRIPTS__", standaloneAfterMain),
    "utf8"
  );
}

async function writeVersion() {
  const version = {
    name: config.name,
    version: config.version,
    date: config.date,
    build: config.build,
    storagePolicy: config.storagePolicy,
    activeTree: config.activeTree,
  };
  await writeFile(path.join(distRoot, "version.json"), `${JSON.stringify(version, null, 2)}\n`, "utf8");
}

async function writeAssetManifest() {
  const files = {
    "main.css": "/static/css/do-wallet-v2-styles.css",
    "main.js": "/static/js/do-wallet-v2-main.js",
    "runtime-before-main.js": "/static/js/do-wallet-v2-runtime-before-main.js",
    "runtime-after-main.js": "/static/js/do-wallet-v2-runtime-after-main.js",
    "index.html": "/index.html",
    "version.json": "/version.json",
    "manifest.json": "/manifest.json",
  };
  for (const file of config.standaloneAfterMain || []) {
    files[`static/js/${file}`] = `/static/js/${file}`;
  }
  const manifest = {
    files,
    entrypoints: [
      "static/css/do-wallet-v2-styles.css",
      "static/js/do-wallet-v2-runtime-before-main.js",
      "static/js/do-wallet-v2-main.js",
      ...(config.standaloneAfterMain || []).map((file) => `static/js/${file}`),
      "static/js/do-wallet-v2-runtime-after-main.js",
    ],
  };
  await writeFile(path.join(distRoot, "asset-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

assertInside(workspaceRoot, distRoot);
await rm(distRoot, { recursive: true, force: true });
await mkdir(distRoot, { recursive: true });
await copyIfExists(path.join(srcRoot, "public"), distRoot);
await mkdir(path.join(distRoot, "static", "js"), { recursive: true });
await cp(
  path.join(srcRoot, "vendor", config.main),
  path.join(distRoot, "static", "js", config.main)
);
await bundleCss();
await bundleRuntime(config.beforeMain, "before-main", "do-wallet-v2-runtime-before-main.js");
await bundleRuntime(config.afterMain, "after-main", "do-wallet-v2-runtime-after-main.js");
for (const file of config.standaloneAfterMain || []) {
  await cp(
    path.join(srcRoot, "runtime", "after-main", file),
    path.join(distRoot, "static", "js", file)
  );
}
await writeIndex();
await writeVersion();
await writeAssetManifest();

console.log(JSON.stringify({
  output: distRoot,
  build: config.build,
  beforeMain: config.beforeMain.length,
  afterMain: config.afterMain.length,
  standaloneAfterMain: (config.standaloneAfterMain || []).length,
  styles: config.styles.length,
}, null, 2));
